stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar --force

variables:
    APPLICATION_NAME: astarte_appengine_api
    CASSANDRA_CLUSTER_NAME: astartetest

mix:test-ci:
    image: elixir:1.5
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix coveralls --exclude cassandra_only
    cache:
        paths:
            - deps
    except:
        - branches@Astarte-NG/astarte_appengine_api

mix:build:
    image: elixir:1.5
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix coveralls --exclude cassandra_only
        - export MIX_ENV=dev
        - mix release
    cache:
        paths:
            - deps
    only:
        - master@Astarte-NG/astarte_appengine_api

mix:release-build:
    image: elixir:1.5
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
    stage: build
    script:
        - export MIX_ENV=prod
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix test --exclude cassandra_only
        - mix release --env=prod
    cache:
        paths:
            - deps
    only:
        - tags@Astarte-NG/astarte_appengine_api
