language: elixir
# Required for Cassandra
sudo: required
services:
  - cassandra
  - rabbitmq
env:
  - CASSANDRA_DB_HOST=localhost RABBITMQ_HOST=localhost MIX_ENV=test
matrix:
  include:
    - elixir: 1.8.1
      otp_release: 21.3
before_script:
  # Needed or Elixir 1.6 will fail due to a non-updated index
  - ~/.mix/rebar3 update
  # Declare events exchange
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo wget http://guest:guest@localhost:15672/cli/rabbitmqadmin -O /usr/local/bin/rabbitmqadmin
  - sudo chmod +x /usr/local/bin/rabbitmqadmin
  - rabbitmqadmin declare exchange name=astarte_events type=direct
after_script:
  - mix coveralls.travis
