language: elixir
# Needed for Cassandra
sudo: required
services:
  - cassandra
  - rabbitmq
  - docker
before_install:
  - docker run -d -p 127.0.0.1:1883:1883 erlio/docker-vernemq:1.3.0
  - docker ps -a
env:
  - CASSANDRA_DB_HOST=localhost RABBITMQ_HOST=localhost CFSSL_API_URL=http://localhost:8888 MIX_ENV=test DOCKER_VERNEMQ_USER_AUTOTEST=autotest
matrix:
  include:
    - elixir: 1.5
      otp_release: 20.2
    # Elixir 1.6 isn't currently supported due to some dependencies - re-enable in the future.
    #- elixir: 1.6
    #  otp_release: 20.2
before_script:
  # Needed or Elixir 1.6 will fail due to a non-updated index
  - ~/.mix/rebar3 update
script:
  - mix test --exclude cassandra_only
after_script:
  - mix coveralls.travis --exclude cassandra_only
